// Overrides where a label differs from its Wikipedia article title.
export const wikiTitle: Record<string, string> = {
  "Renaissance Humanism": "Renaissance humanism",
  "The Enlightenment": "Age of Enlightenment",
  "Early Renaissance": "Italian Renaissance painting",
  "Venetian Renaissance": "Venetian painting",
  "Dutch Golden Age": "Dutch Golden Age painting",
  "Neoplatonism & Skepticism": "Renaissance Platonism",
  "The Reformation": "Reformation",
  "Social Contract & the State": "Social contract",
  "Gutenberg's press": "Printing press",
  "Columbus · New World": "Voyages of Christopher Columbus",
  "Luther's 95 Theses": "Ninety-five Theses",
  "Copernican revolution": "Copernican Revolution",
  "Newton's Principia": "Philosophiæ Naturalis Principia Mathematica",
  "American Revolution": "American Revolutionary War",
  "Waterloo · Congress of Vienna": "Congress of Vienna",
  "Darwin's Origin of Species": "On the Origin of Species",
  "Einstein · relativity": "Theory of relativity",
  "Russian Revolution": "Russian Revolution",
  "Wall Street Crash": "Wall Street Crash of 1929",
  "Moon landing": "Apollo 11",
  "Fall of the Berlin Wall": "Berlin Wall",
  "The World Wide Web": "World Wide Web",
  "September 11": "September 11 attacks",
  "The smartphone": "Smartphone",
  "Generative AI": "Generative artificial intelligence",
  "Pre-Raphaelites": "Pre-Raphaelite Brotherhood",
  "Realism": "Realism (arts)",
  "Decadence": "Decadent movement",
  "Symbolism": "Symbolism (arts)",
  "Abstraction": "Abstract art",
  "Constructivism / De Stijl": "Constructivism (art)",
  "Performance / Land / Body": "Performance art",
  "Postmodernism": "Postmodern art",
  "Relational / Institutional": "Relational art",
  "Post-Internet / New Media": "Post-Internet art",
  "AI / Post-Digital / Now": "Artificial intelligence art",
  "German Idealism": "German idealism",
  "Schopenhauer": "Arthur Schopenhauer",
  "Nietzsche": "Friedrich Nietzsche",
  "Bergsonism": "Henri Bergson",
  "Phenomenology": "Phenomenology (philosophy)",
  "Critical Theory": "Frankfurt School",
  "Poststructuralism": "Post-structuralism",
  "Postmodern Theory": "Postmodernism",
  "Posthumanism & Accelerationism": "Posthumanism"
}
